### ISSUE TITLE
Unicode letters in source break evaluating Lua

### ISSUE THREAD

**Issue by moll** [jmettraux/rufus-lua#36]
Hey,

I noticed characters from the end of the source string get stripped and it seems to be a Unicode length issue. I believe if you replace the call to `length` in https://github.com/jmettraux/rufus-lua/blob/0f6e859ffbfa95b798061195d6882dd28a14d88e/lib/rufus/lua/state.rb#L94 with a call to `bytesize`, things should work.

**Comment by moll** [comment]
A workaround till then:
```ruby
source = File.read(source)
source.define_singleton_method(:length, &source.method(:bytesize))
```

**Comment by jmettraux** [comment]
Hello,

any way for me to reproduce the issue?

**Comment by moll** [comment]
You could try the following, I believe:

```ruby
require "rufus-lua"
lua = Rufus::Lua::State.new
lua.eval(%(print("Head ööd, Möll!")))
```

**Comment by jmettraux** [comment]
Thanks a lot, your fix does it, if not please tell me. I think I'll release 1.1.3 soon.

**Comment by moll** [comment]
Yay, thanks!
