### ISSUE TITLE
luajit support

### ISSUE THREAD

**Issue by radiospiel** [jmettraux/rufus-lua#37]
This is more a question that a real issue: is it possible to integrate luajit using rufus-lua?

**Comment by jmettraux** [comment]
Hello,

I'm sorry, I have never tried, I cannot answer.

Kind regards.

**Comment by radiospiel** [comment]
Thanks for your quick answer. FYI: I just gave it a try, it does not work:

    LUA_LIB=/usr/local/lib/libluajit-5.1.dylib ruby hello-lua.rb

fails with a crash. Only tried that on OSX 10.11.

**Comment by jmettraux** [comment]
Thanks!

**Comment by radiospiel** [comment]
A final addition to whoever stumples across this entry: it seems that luajit, on MacOS, requires the main executable (which I guess to mean the ruby binary itself, when embedding into ruby) to be compiled with extra options, or else luaL_newstate cannot create a state: see http://stackoverflow.com/questions/20858911/lua-open-returns-null-using-luajit

This, I guess, means there is no way to embed luajit into any ruby on MacOS, unless one custom-builds ruby
