### ISSUE TITLE
Support lua 5.3 or 5.2

### ISSUE THREAD

**Issue by skandragon** [jmettraux/rufus-lua#38]
How hard would it be to support at least 5.2?  I need to execute some code in a secure sandbox, and this code is currently written for 5.2.

Another option I have is to use a web service to execute my code, but that opens up another rat's nest.

**Comment by nathanaeljones** [comment]
If Lua followed semver, 5.1 would be v6, 5.2 would be v7. Sandboxing is completely different, and I don't know that the stack is binary compatible.

That said, rufus-lua uses the `ffi` gem, which is a pleasure to use. Nothing could be easier to hack on. Give it a try and report back!

**Comment by skandragon** [comment]
I'm trying to hack on it already.  So far, all I am getting is tons of crashes (Abort trap 6, which I am sure is an illegal access)

The first step is to convert over to the newer methods -- for example, lua_call() is gone, lua_pcall() seems to be gone (although it's still documented!) leaving only lua_pcallk().

**Comment by jmettraux** [comment]
Hello @skandragon

I currently have no plans to support Lua > 5.1 with rufus-lua. Please steal all the things you need here and start your own project.

Happy new year!

**Comment by skandragon** [comment]
OK, good to know.  May I ask why?  Is 5.1 just all you need and you don't want the complication of supporting more than one?

**Comment by jmettraux** [comment]
Exactly.

Best regards.
