### ISSUE TITLE
Report the lua line number for exceptions raised by Ruby callbacks

### ISSUE THREAD

**Issue by pjungwir** [jmettraux/rufus-lua#39]
Suppose you define a Ruby callback like this:

    s = Rufus::Lua::State.new
    s.function("example.find_it") do |id|
      if id == 5
        raise "Not found: #{id}"
      else
        "got it"
      end
    end

And then you run a Lua script like this:

    s.eval(<<-EOS)
      do
        example.find_it(7)
        example.find_it(6)
        example.find_it(5)
      end
    EOS

It would be nice to know that the script failed on line 4 of the Lua code, but I can't see any way to do this. I looked through the gem's code but couldn't figure out how to patch it myself. Any suggestions?

Thanks for this by the way! Embedding Lua in a Ruby project is very nice!

**Comment by jmettraux** [comment]
Hello,

I will take the time to look into this during the week-end.

**Comment by jmettraux** [comment]
I am sorry, I took some time to look at that during the week-end (in September yes) but I couldn't find an easy way to solve that.

I am afraid I don't have the time to add features to this library, but I will still try to nail this in the coming weeks.

Sorry again.

**Comment by pjungwir** [comment]
Thank you for taking a stab at it! Being able to embed Lua in a Rails app for user scripting is pretty awesome by the way. This gem has really made a difference to an organization I contract with. We expose an API of various functions about the app and power users can write Lua scripts sort of like writing Excel functions. (For security we use `setfenv` to remove access to all but a few whitelisted built-in functions.) I am hoping to write a blog post about it soon and will send you a link when it's published.

In the meantime, I've been working around this issue like this: Instead of having users call the implemented-in-Ruby function directly, I have them call a wrapper that is implemented in Lua. The Ruby function returns a table something like `{ERROR=nil, RESULT=5}`, and the Lua wrapper checks for an error and raises if necessary. We use `error(ret.ERROR, 2)` so that the user sees a line number from their own code, not our wrapper. It is working very well!

**Comment by jmettraux** [comment]
(archiving repository)
