### ISSUE TITLE
Try /usr/lib/liblua5.1.so before /usr/lib/liblua.so

### ISSUE THREAD

**Issue by moll** [jmettraux/rufus-lua#41]
Hey,

I too was briefly puzzled why Rufus was throwing `Function 'lua_call' not found` before noticing the Lua v5.1 requirement. That's a fine requirement, but it'd be nice if it also tried to go for the v5.1 before stumbling upon later Luas. I'm guessing it's because of the globs in `lib.rb`: https://github.com/jmettraux/rufus-lua/blob/d0ceaa15917e6c3f03dc17e4f3d3cf5871ee9451/lib/rufus/lua/lib.rb#L15-L25

Arch Linux, for example, permits having all Lua versions in `/usr/lib`, but defaults the unversioned one to the latest. How about trying `/usr/lib/liblua5.1.so` before the unversioned one so it'd work out of the box?

**Comment by jmettraux** [comment]
Excellent point.

I will enforce that.

Thanks.

**Comment by jmettraux** [comment]
@moll Hello, would the above commit solve the issue?

Thanks in advance.

**Comment by moll** [comment]
Hey! I suppose so. Although I'd remove `/usr/*/lib` from it and not be _too_ permissive. My `/usr`, for example, contains directories you definitely don't want to look for libs in, like `mingw32` and other 32-bit libraries. Same for `/opt`. We're talking about running possibly untrusted code, after all.

Backing up a little, why have hard-coded paths here at all? That doesn't seem to be the job of a library _loading_ another library, but of a system component. Ruby's FFI itself seems to indicate it does some searching in https://www.rubydoc.info/github/ffi/ffi/FFI/Library. That's surely a more portable choice that, who knows, may work on Windows, too. ;) I, in turn, would expect Ruby's FFI to honor the system's `/etc/ld.so.conf` removing Rufus entirely from the job of handling everyone's custom library placements.

**Comment by jmettraux** [comment]
OK, I think I will simply disable this "autosearch" and release a 1.2.

**Comment by jmettraux** [comment]
Released 1.1.5, works out of the box on OpenBSD 6.3, Debian GNU/Linux and OSX.

Please tell me if there is anything wrong.

Thanks.

**Comment by moll** [comment]
Great! Thanks. I'll report back should it not work next time I upgrade Rufus!
