### ISSUE TITLE
Raised exception lost in lua function

### ISSUE THREAD

**Issue by HansBug** [jmettraux/rufus-lua#42]
The two function (`func1` and `func2`) is defined as below :
```ruby
def func1
  lua = Rufus::Lua::State.new 
  lua.function :ex do
    raise RuntimeError
  end
  lua.function :cx do |x|
    x + 1
  end
  lua.eval("l = cx(1); ex(); return {l = l}")
  lua.close()
end

def func2
  lua = Rufus::Lua::State.new 
  lua.function :ex do
    raise RuntimeError
  end
  lua.function :cx do |x|
    x + 1
  end
  lua.eval("l = cx(1); ex(); cx(2); return {l = l}")
  lua.close()
end
```

When `func1` is called, a RuntimeError can be caught from outside (this is the normal behavior). But when `func2` is called, **nothing will happen even the `ex` function which raise a RuntimeError is called.**

I tried, I find that when a user-defined function is called in lua with a raised ruby exception, then another used-define function is called (no exception) just follow the last one, the ruby exception will lost.

**Comment by jmettraux** [comment]
@HansBug Thanks for the issue report.

I've dug around but couldn't find an easy way out for now.

Please stay tuned.

**Comment by HansBug** [comment]
Okay, thanks a lot. (I wish this issue can be fixed as soon as possible because it's associated with a very important part in my project. T_T)

**Comment by jmettraux** [comment]
Have tried with [rlua](https://github.com/whitequark/rlua) (as linked from https://github.com/jmettraux/rufus-lua#other-ruby-and-lua-bridges--connectors)? It uses Lua 5.3, it might be quicker than to wait for me (and maybe the problem is in Lua (5.1) itself...).

**Comment by HansBug** [comment]
Okay, thank you, I'll take a look. Good luck! :)

**Comment by HansBug** [comment]
Some additional information: The `rlua` gem (version `1.2`, the latest official released version) is based on lua5.1 (the same as `rufus-lua`), I try this issue in `rlua`, it behaves correctly.
So I don't think this issue is associated with lua5.1 .

**Comment by jmettraux** [comment]
@HansBug Great piece of information, thank you very much! That helps a lot!

**Comment by jmettraux** [comment]
(archiving repository)
