### ISSUE TITLE
lua@5.1 homebrew formula is disabled

### ISSUE THREAD

**Issue by smshuja** [jmettraux/rufus-lua#44]
Hello @jmettraux 
Thank you for your amazing work on this gem.

lua 5.1 formula had been [deprecated](https://formulae.brew.sh/formula/lua@5.1) for quite sometime. Now it has been disabled.

Do you have any plans to support a newer lua version?

**Comment by jmettraux** [comment]
Hello @smshuja, thanks for your message.

Sorry, I have no plan to continue work on rufus-lua. I will flag the repository.
